### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by ghost** [NimaKhajehpour/WikiAnime#2]
Hi,

App crashes shortly after opening it.

Crash Log:

```
type: crash
osVersion: google/bluejay/bluejay:13/TQ1A.230105.001.A2/2023011000:user/release-keys
package: com.nima.wikianime:1
process: com.nima.wikianime
processUptime: 1505 + 240 ms

java.lang.IllegalArgumentException: Unknown color
	at android.graphics.Color.parseColor(Color.java:1390)
	at com.nima.wikianime.components.ThumbnailItemKt.ThumbnailItem(ThumbnailItem.kt:91)
	at com.nima.wikianime.screens.HomeScreenKt$HomeScreen$1$2$4$1$invoke$$inlined$items$default$4.invoke(LazyDsl.kt:424)
	at com.nima.wikianime.screens.HomeScreenKt$HomeScreen$1$2$4$1$invoke$$inlined$items$default$4.invoke(LazyDsl.kt:145)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.foundation.lazy.LazyListItemsSnapshot.Item(LazyListItemProviderImpl.kt:90)
	at androidx.compose.foundation.lazy.LazyListItemProviderImpl.Item(LazyListItemProviderImpl.kt:117)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1$1.invoke(LazyLayoutItemContentFactory.kt:119)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1$1.invoke(LazyLayoutItemContentFactory.kt:118)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(LazyLayoutItemContentFactory.kt:118)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(LazyLayoutItemContentFactory.kt:110)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$2$1$1.invoke(SubcomposeLayout.kt:771)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$2$1$1.invoke(SubcomposeLayout.kt:448)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3248)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3238)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3238)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3173)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:950)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3848)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:468)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:441)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:432)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.precompose(SubcomposeLayout.kt:637)
	at androidx.compose.ui.layout.SubcomposeLayoutState.precompose(SubcomposeLayout.kt:226)
	at androidx.compose.foundation.lazy.layout.LazyLayoutPrefetcher.run(LazyLayoutPrefetcher.android.kt:171)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by NimaKhajehpour** [comment]
@Tabarium  Hello and thanks for the feedback on the app crash. the app was tested many times for the suggested color on the cards and i made sure that it wont happen on release. sadly it seems like it happened for you. would you mind re installing the app from the github release and let me know if it happens again. also can you let me know what anime is in the view when the crash happens. this helps me speed up the process of finding the cause of it.
thanks again for the feedback. :heart:

**Comment by NimaKhajehpour** [comment]
> Hi,
> 
> App crashes shortly after opening it.
> 
> Crash Log:
> 
> ```
> type: crash
> osVersion: google/bluejay/bluejay:13/TQ1A.230105.001.A2/2023011000:user/release-keys
> package: com.nima.wikianime:1
> process: com.nima.wikianime
> processUptime: 1505 + 240 ms
> 
> java.lang.IllegalArgumentException: Unknown color
> 	at android.graphics.Color.parseColor(Color.java:1390)
> 	at com.nima.wikianime.components.ThumbnailItemKt.ThumbnailItem(ThumbnailItem.kt:91)
> 	at com.nima.wikianime.screens.HomeScreenKt$HomeScreen$1$2$4$1$invoke$$inlined$items$default$4.invoke(LazyDsl.kt:424)
> 	at com.nima.wikianime.screens.HomeScreenKt$HomeScreen$1$2$4$1$invoke$$inlined$items$default$4.invoke(LazyDsl.kt:145)
> 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
> 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
> 	at androidx.compose.foundation.lazy.LazyListItemsSnapshot.Item(LazyListItemProviderImpl.kt:90)
> 	at androidx.compose.foundation.lazy.LazyListItemProviderImpl.Item(LazyListItemProviderImpl.kt:117)
> 	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1$1.invoke(LazyLayoutItemContentFactory.kt:119)
> 	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1$1.invoke(LazyLayoutItemContentFactory.kt:118)
> 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
> 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
> 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
> 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
> 	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(LazyLayoutItemContentFactory.kt:118)
> 	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(LazyLayoutItemContentFactory.kt:110)
> 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
> 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
> 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$2$1$1.invoke(SubcomposeLayout.kt:771)
> 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$2$1$1.invoke(SubcomposeLayout.kt:448)
> 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
> 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
> 	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
> 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3248)
> 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3238)
> 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
> 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
> 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3238)
> 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3173)
> 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
> 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:950)
> 	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3848)
> 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
> 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:468)
> 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:441)
> 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:432)
> 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.precompose(SubcomposeLayout.kt:637)
> 	at androidx.compose.ui.layout.SubcomposeLayoutState.precompose(SubcomposeLayout.kt:226)
> 	at androidx.compose.foundation.lazy.layout.LazyLayoutPrefetcher.run(LazyLayoutPrefetcher.android.kt:171)
> 	at android.os.Handler.handleCallback(Handler.java:942)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:201)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:7878)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
> 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
> ```

**Comment by ghost** [comment]
Hi,

I downloaded it at first from fdroid but deleted it and then directly from github.

I encounter the same problem, the app crashes.

I swipe up and down and to the left and right and then it crashes sometimes.

**Comment by NimaKhajehpour** [comment]
@Tabarium Thanks for the update, i found the issue and i'm working on fixing it right now.

**Comment by NimaKhajehpour** [comment]
@Tabarium Hopefully this update get rid of the bug and the app should be usable now. sorry for the inconvenience and the bug. let me know if its fixed and thanks again for the report and using the app :heart:

**Comment by ghost** [comment]
Works 😀😀😀

Didnt crashed

**Comment by NimaKhajehpour** [comment]
Again thanks for letting me know the bug existed. Enjoy the app and feel free to recommend it to your anime loving friends too. 
will try to publish the update ASAP to f-droid. but for now i guess users can download it from here.
